repos:
  - repo: https://github.com/twu/skjold
    rev: "v0.6.1"
    hooks:
      - id: skjold
        verbose: true
        args: [ "-s", "pyup" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        language_version: python3.10

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.13.0"
    hooks:
      - id: django-upgrade
        args: [ --target-version, "4.1" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/python/black
    rev: "23.3.0"
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        language_version: python3.10
        args: [ --skip-string-normalization, -l 120 ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        exclude: tests/
        args: [ '--skip', 'B324,B311,B110,B101,B105' ]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.1
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: ^.*\b(migrations)\b.*$
        types: [ python ]
        args:
          - --errors-only
          - --rcfile=.pylintrc
          - --load-plugins=pylint_django

  - repo: https://github.com/AliYmn/conventional-commits-check
    rev: V1.0.0  # Use the latest release version
    hooks:
      - id: conventional-commits-check
        stages: [commit-msg]
