# Generated by Django 4.1.7 on 2023-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
