# Generated by Django 4.1.7 on 2023-04-16 17:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_userprofile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 17, 23, 44, 486741, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.CharField(max_length=64),
        ),
    ]
