# Generated by Django 4.1.7 on 2023-04-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_logentry_created_at_logentry_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='timestamp',
        ),
    ]
