# Generated by Django 4.1.7 on 2023-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_remove_logentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='data',
            field=models.TextField(default='Pending...'),
        ),
    ]
