# Generated by Django 4.1.7 on 2023-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_logentry_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='secure_hash',
            field=models.CharField(default='Pending...', max_length=100),
        ),
    ]
