# Generated by Django 4.1.7 on 2023-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_logentry_blockchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='data_hash',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='secure_hash',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='blockchain',
            field=models.CharField(choices=[('eth', 'Ethereum')], default='eth', max_length=4),
        ),
    ]
