# Generated by Django 4.1.7 on 2023-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_remove_logentry_data_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='data_hash',
            field=models.CharField(default='Pending...', max_length=100),
        ),
    ]
